DjangoProjectAlckemy/StockControl/StockControl/urls.py
from django.contrib import admin
from django.urls import path
from compra import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('listar-productos/', views.listar_productos, name='listar_productos'),
     path('listar-proveedores/', views.listar_proveedores, name='listar_proveedores'),
    path('agregar-producto/', views.agregar_productos, name='agregar_producto'),
    path('agregar-proveedor/', views.agregar_proveedor, name='agregar_proveedor'),
    path('', views.pagina_inicio, name='pagina_inicio'),
]

DjangoProjectAlckemy/StockControl/compra/models.py
from django.db import models


class Proveedor(models.Model): ## debemos usar models.model ya que nos aplia el uso de funciones 
    nombre = models.CharField(max_length=100);
    apellido = models.CharField(max_length=100);
    dni = models.IntegerField();
    
    def __str__(self): ## con el metdoo __str__ hacemos que nos devuelva un objeto en string, o cadena de texto como sea
        return f'{self.nombre} {self.apellido} ';
    
class Producto(models.Model):
    nombre = models.CharField(max_length=100);
    precio = models.DecimalField(max_digits=10, decimal_places=2);
    stock_actual = models.IntegerField();
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE); ## aca hacemos referencia a una clave forranea, que cuando borremos el proveedor del otro modelo tambien se borre de aqui
    
    def __str__(self): ## de nuevo pasamos aca el producto en nombre, en cadena de texto
        return f'{self.nombre} ';

DjangoProjectAlckemy/StockControl/compra/forms.py
from django import forms
from .models import Proveedor  ##no olvidarnos importar esto porque no va andar ni para adelante ni para atras, 
from .models import Producto ## lo de arriba x2
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class ProveedorForm(forms.ModelForm): ##aprovechando las funciones de django con forms tenemos maas funciones
    class Meta: #define metadatos adicionales para el formulario. es una clase anidada de forms
        model = Proveedor; ##avisamos que esta clase esta vinculada a nuestro modelo de Proveedor
        fields = ['nombre', 'apellido', 'dni'] ##avisamos que datos vamos  a tneer el form, parace ser algo asi como descontruction de react en inversa
    
    def __init__(self, *args, **kwargs):
        super(ProveedorForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Agregar Proveedor'))
    
          
class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'precio', 'stock_actual', 'proveedor']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'precio': forms.NumberInput(attrs={'class': 'form-control'}),
            'stock_actual': forms.NumberInput(attrs={'class': 'form-control'}),
            'proveedor': forms.Select(attrs={'class': 'form-select'})
        }

DjangoProjectAlckemy/StockControl/compra/views.py
from django.shortcuts import render,redirect
from .models import Producto, Proveedor;
from .forms import ProductoForm, ProveedorForm;
from django.views.decorators.csrf import csrf_protect ## esto para que no nos hagan  ataques csrf :c  abajo deje un mini resumen de que son ataques csrf

@csrf_protect
def pagina_inicio(request):
    productos = Producto.objects.all()
    return render(request, 'pagina_inicio.html', {'productos': productos})

##funcion para ver los productos que ya cargamos
@csrf_protect 
def listar_productos(request): ## representa la solicitud HTTP recibida por el servidor.
    productos = Producto.objects.all() #para recuperar todos los objetos de tipo Producto de la base de datos. 
    return render(request, 'listar_productos.html', {'productos': productos});


@csrf_protect 
def listar_proveedores(request): ## representa la solicitud HTTP recibida por el servidor.
    proveedores = Proveedor.objects.all() #para recuperar todos los objetos de tipo Proveedor de la base de datos. 
    return render(request, 'listar_proveedores.html', {'proveedores': proveedores});


##funcion para agregar productos
@csrf_protect
def agregar_productos(request): ## representa la solicitud HTTP recibida
    if request.method == 'POST': 
        form = ProductoForm(request.POST)
        if form.is_valid(): # si esta correcto lo guardo 
            form.save()
            return redirect('listar_productos');
        else:
            ##este lo usamos para avisar que algo no esta bien en el formulario, para avisar de ello al usuario
            return render(request,'agregar_producto.html', {'form': form, 'error_message': '¡El formulario no es válido! Por favor, revise los datos ingresados.'})
    else:
        form = ProductoForm();
    return render(request, 'agregar_producto.html', {'form': form});

@csrf_protect
def agregar_proveedor(request): 
     if request.method == 'POST':
          form = ProveedorForm(request.POST)
          if form.is_valid():
               form.save()  
               return redirect('listar_proveedores') ##aca podemos ponerlo en listar:productos en caso que necesitemos cambiar la vista donde lo mandamos
     else:
         form = ProveedorForm();
     return render(request, 'agregar_proveedor.html', {'form': form});
 
 
 ##CSRF es un ataque que explota la confianza entre un navegador y un sitio web al aprovechar las sesiones activas del usuario en múltiples sitios. Las protecciones contra CSRF son importantes para garantizar la seguridad de las aplicaciones web.

DjangoProjectAlckemy/StockControl/compra/templates/agregar_producto.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Producto</title>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-dark text-white">
                        <h3 class="card-title">Agregar Nuevo Producto</h3>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_nombre" class="form-label">Nombre</label>
                                {{ form.nombre }}
                            </div>
                            <div class="mb-3">
                                <label for="id_precio" class="form-label">Precio</label>
                                {{ form.precio }}
                            </div>
                            <div class="mb-3">
                                <label for="id_stock_actual" class="form-label">Stock Actual</label>
                                {{ form.stock_actual }}
                            </div>
                            <div class="mb-3">
                                <label for="id_proveedor" class="form-label">Proveedor</label>
                                {{ form.proveedor }}
                            </div>
                            
                            <button type="submit" class="btn btn-dark">Agregar Producto</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% bootstrap_javascript %}
</body>
</html>

DjangoProjectAlckemy/StockControl/compra/templates/agregar_proveedor.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Proveedor</title>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-dark text-white">
                        <h3 class="card-title">Agregar Nuevo Proveedor</h3>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_nombre" class="form-label">Nombre</label>
                                {{ form.nombre }}
                            </div>
                            <div class="mb-3">
                                <label for="id_apellido" class="form-label">Apellido</label>
                                {{ form.apellido }}
                            </div>
                            <div class="mb-3">
                                <label for="id_dni" class="form-label">DNI</label>
                                {{ form.dni }}
                            </div>
                            <button type="submit" class="btn btn-dark">Agregar Proveedor</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% bootstrap_javascript %}
</body>
</html>

DjangoProjectAlckemy/StockControl/compra/templates/listar_productos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% load static %}
    <title>Listado de Productos</title>
</head>
<body>
    <div class="container">
        <h1>Listado de Productos</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Precio</th>
                    <th>Stock Actual</th>
                    <th>Proveedor</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                <tr>
                    <td>{{ producto.nombre }}</td>
                    <td> $ {{  producto.precio }}</td>
                    <td>{{ producto.stock_actual }}</td>
                    <td>{{ producto.proveedor.nombre }} {{ producto.proveedor.apellido }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

DjangoProjectAlckemy/StockControl/compra/templates/listar_proveedores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    <title>Listado de Proveedores</title>
</head>
<body>
    <div class="container">
        <h1>Listado de Proveedores</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>DNI</th>
                </tr>
            </thead>
            <tbody>
                {% for proveedor in proveedores %}
                <tr>
                    <td>{{ proveedor.nombre }}</td>
                    <td>{{ proveedor.apellido }}</td>
                    <td>{{ proveedor.dni }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

DjangoProjectAlckemy/StockControl/compra/templates/pagina_inicio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bienvenido a StockControl</title>
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="../static/css/pagina_inicio.css">
</head>
<body class="bg-light d-flex flex-column justify-content-center align-items-center">

    <h1 class="mb-5 mt-5 mx-10 h1">Bienvenido a StockControl</h1>

    <div class="container mt-1 text">
        <div class="row justify-content-center">
            <div class="col-md-3 opcion  text-center">
                <a class="btn btn-outline-secondary" href="{% url 'agregar_proveedor' %}">
                    <img class="img-fluid img-thumbnail " src="{% static '../static/img/vendedor.jpg' %}" alt="Proveedores" class="img-fluid">
                    Añadir Proveedor
                </a>
            </div>
            <div class="col-md-3 opcion  text-center text-body-secondary">
                <a class="btn btn-outline-secondary" href="{% url 'agregar_producto' %}">
                    <img class="img-fluid img-thumbnail " src="{% static '../static/img/product.jpg' %}" alt="Productos">
                    Añadir Producto
                </a>
            </div>
            <div class="col-md-3 opcion  text-center">
                <a class="btn btn-outline-secondary" href="{% url 'listar_productos' %}">
                    <img  class="img-fluid img-thumbnail "src="{% static '../static/img/listProduct.jpg' %}" alt="Listado de Productos" class="img-fluid">
                    Listar Productos
                </a>
            </div>
            <div class="col-md-3 opcion  text-center  ">
                <a class="btn btn-outline-secondary" href="{% url 'listar_proveedores' %}">
                    <img class="img-fluid img-thumbnail " src="{% static '../static/img/listVendedor.jpg' %}" alt="Listado de Proveedores" class="img-fluid">
                    Listar Proveedores
                </a>
            </div>
        </div>
    </div>
</body>
</html>